name: Build & Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  build-deploy:
    name: Build and Deploy spring boot application
    runs-on: ubuntu-latest
    services:
      mysql-master:
        image: mysql:5.7
        ports:
          - 3306/tcp
        env:
          MYSQL_DATABASE: avada_slj_kcms03
          MYSQL_USER: avada_slj_kcms03
          MYSQL_PASSWORD: m8rqH2D1BC
          MYSQL_HOST: localhost
          MYSQL_ROOT_PASSWORD: m8rqH2D1BC
        options: >-
          --name=localhost
          --health-cmd="mysqladmin ping"
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Tomcat Deploy
        run: curl -v -u robot:K4QU@mJ!djX4D8X2 -T /home/runner/work/kino_cms/kino_cms/target/Kino_CMS_O_Lesyk.war -F overwrite=true 'https://slj.avada-media-dev1.od.ua/manager/text/deploy?path=/Kino_CMS_O_Lesyk'