name: Build & Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  build-deploy:
    name: Build and Deploy spring boot application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml
        env:
          MYSQL_HOSTNAME: avada_slj_kcms03
          MYSQL_PORT: 3306
          MYSQL_USERNAME: avada_slj_kcms03
          MYSQL_PASSWORD: m8rqH2D1BC

      - name: Build application
        run: |
          mvn clean
          mvn -B package --file pom.xml